gluggi:
    path: /
    defaults:
        _controller: GluggiBundle:Gluggi:index


gluggi.type:
    path: /{type}/
    defaults:
        _controller: GluggiBundle:Gluggi:type
    requirements:
        type: '%gluggi.routing.requirements.key%'


gluggi.component:
    path: /{type}/{key}/
    defaults:
        _controller: GluggiBundle:Gluggi:component
    requirements:
        type: '%gluggi.routing.requirements.key%'
        key: '%gluggi.routing.requirements.key%'
