gluggi:
    path: /
    defaults:
        _controller: Becklyn\GluggiBundle\Controller\GluggiController::index


gluggi.component:
    path: /{type}/{key}/
    defaults:
        _controller: Becklyn\GluggiBundle\Controller\GluggiController::component
    requirements:
        type: '%gluggi.routing.requirements.key%'
        key: '%gluggi.routing.requirements.key%'
