parameters:
    gluggi.routing.requirements.key: '[a-z0-9-_]+'

services:

    Becklyn\GluggiBundle\Controller\GluggiController:
        tags: ['controller.service_arguments']
        autoconfigure: true

    Becklyn\GluggiBundle\Assets\LayoutAssets:
        - '@Becklyn\GluggiBundle\Configuration\GluggiConfig'
        - '@assets.packages'

    Becklyn\GluggiBundle\Component\GluggiFinder:
        - '@Becklyn\GluggiBundle\ComponentType\ComponentTypeRegistry'

    Becklyn\GluggiBundle\LayoutBundleIntegration\BundlePaths:
        arguments:
            - '@kernel'
        public: false

    Becklyn\GluggiBundle\ComponentType\ComponentTypeRegistry:
        arguments:
            - '@Becklyn\GluggiBundle\LayoutBundleIntegration\BundlePaths'
        public: false

    Becklyn\GluggiBundle\Component\ComponentConfiguration:
        arguments:
            - '@twig'

    Becklyn\GluggiBundle\Twig\GluggiTwigExtension:
        arguments:
            - '@Becklyn\GluggiBundle\Component\GluggiFinder'
            - '@Becklyn\GluggiBundle\Configuration\GluggiConfig'
            - '@service_container'
        tags:
            - { name: twig.extension }
        public: false

    Becklyn\GluggiBundle\Configuration\GluggiConfig:
        arguments:
            - ~ # all parameters set via the extension
            - ~
            - []
            - []
            - []
            - []
