parameters:
    gluggi.routing.requirements.key: '[a-z0-9-_]+'

services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\GluggiBundle\Assets\LayoutAssets: ~
    Becklyn\GluggiBundle\Component\ComponentConfiguration: ~
    Becklyn\GluggiBundle\Component\GluggiFinder: ~

    Becklyn\GluggiBundle\ComponentType\ComponentTypeRegistry:
        arguments:
            $templatesDefaultPath: '%twig.default_path%'

    Becklyn\GluggiBundle\Configuration\GluggiConfig: ~
    Becklyn\GluggiBundle\Controller\GluggiController: ~
    Becklyn\GluggiBundle\Twig\GluggiTwigExtension: ~
