parameters:
    gluggi.routing.requirements.key: '[a-z0-9-_]+'

services:

    gluggi.assets:
        class: Becklyn\GluggiBundle\Assets\LayoutAssets
        arguments:
            - '@gluggi.config'
            - '@assets.packages'

    gluggi.finder:
        class: Becklyn\GluggiBundle\Component\GluggiFinder
        arguments:
            - '@gluggi.component_type_registry'

    gluggi.layout.bundle_paths:
        class: Becklyn\GluggiBundle\LayoutBundleIntegration\BundlePaths
        arguments:
            - '@kernel'
        public: false

    gluggi.component_type_registry:
        class: Becklyn\GluggiBundle\ComponentType\ComponentTypeRegistry
        arguments:
            - '@gluggi.layout.bundle_paths'
        public: false

    gluggi.component.configuration:
        class: Becklyn\GluggiBundle\Component\ComponentConfiguration
        arguments:
            - '@twig'

    gluggi.twig.extension:
        class: Becklyn\GluggiBundle\Twig\GluggiTwigExtension
        arguments:
            - '@gluggi.finder'
            - '@gluggi.config'
            - '@service_container'
        tags:
            - { name: twig.extension }
        public: false

    gluggi.config:
        class: Becklyn\GluggiBundle\Configuration\GluggiConfig
        arguments:
            - ~ # all parameters set via the extension
            - ~
            - []
            - []
            - []
