parameters:
    gluggi.routing.requirements.key: '[a-z0-9-_]+'

services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\GluggiBundle\Component\ComponentConfiguration: ~
    Becklyn\GluggiBundle\Component\GluggiFinder: ~
    Becklyn\GluggiBundle\ComponentType\ComponentTypeRegistry: ~
    Becklyn\GluggiBundle\Configuration\GluggiConfig: ~
    Becklyn\GluggiBundle\Controller\GluggiController: ~

    Becklyn\GluggiBundle\Paths\LayoutDirectory:
        arguments:
            $twigDefaultPath: '%twig.default_path%'

    Becklyn\GluggiBundle\Twig\GluggiTwigExtension: ~

    Becklyn\GluggiBundle\Serializer\TypesSerializer: ~
