parameters:
    gluggi.routing.requirements.key: '[a-z0-9-_]+'

services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\GluggiBundle\:
        resource: '../../*'
        exclude: '../../{Data,Exception,Resources,GluggiBundle.php}'

    Becklyn\GluggiBundle\Paths\LayoutDirectory:
        arguments:
            $twigDefaultPath: '%twig.default_path%'
